/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param name The name of the link
 * @param source The Source-Card
 * @param target The Destination-Card
 */


data class CreateLinkEntity (

    /* The name of the link */
    @Json(name = "name")
    val name: kotlin.String,

    /* The Source-Card */
    @Json(name = "source")
    val source: java.util.UUID,

    /* The Destination-Card */
    @Json(name = "target")
    val target: java.util.UUID

)

