/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param label The learning system's label
 * @param boxLabels A List of Strings representing box labels.
 */


data class CreateLearningSystemEntity (

    /* The learning system's label */
    @Json(name = "label")
    val label: kotlin.String,

    /* A List of Strings representing box labels. */
    @Json(name = "boxLabels")
    val boxLabels: kotlin.collections.List<kotlin.String>

)

