/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param label 
 * @param target 
 */


data class LinkEntity (

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "target")
    val target: java.util.UUID? = null

)

