/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The UUID of the category that is to be updated.
 * @param label The category label
 * @param subCategories An array of child-category UUIDs.
 */


data class UpdateCategoryEntity (

    /* The UUID of the category that is to be updated. */
    @Json(name = "id")
    val id: java.util.UUID,

    /* The category label */
    @Json(name = "label")
    val label: kotlin.String,

    /* An array of child-category UUIDs. */
    @Json(name = "subCategories")
    val subCategories: kotlin.collections.List<java.util.UUID>

)

