/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The UUID of the learning system that is to be updated.
 * @param label The learning system's label
 * @param boxLabels An array of child-category UUIDs.
 */


data class UpdateLearningSystemEntity (

    /* The UUID of the learning system that is to be updated. */
    @Json(name = "id")
    val id: java.util.UUID,

    /* The learning system's label */
    @Json(name = "label")
    val label: kotlin.String,

    /* An array of child-category UUIDs. */
    @Json(name = "boxLabels")
    val boxLabels: kotlin.collections.List<kotlin.String>

)

