/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.LinkEntity

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id The UUID of the card that is to be updated.
 * @param question The question to be asked
 * @param answer The answer to the question
 * @param tag Tag
 * @param categories Zugehörige Kategorien
 * @param links 
 */


data class UpdateCardEntity (

    /* The UUID of the card that is to be updated. */
    @Json(name = "id")
    val id: java.util.UUID,

    /* The question to be asked */
    @Json(name = "question")
    val question: kotlin.String,

    /* The answer to the question */
    @Json(name = "answer")
    val answer: kotlin.String,

    /* Tag */
    @Json(name = "tag")
    val tag: kotlin.String,

    /* Zugehörige Kategorien */
    @Json(name = "categories")
    val categories: kotlin.collections.List<java.util.UUID>,

    @Json(name = "links")
    val links: kotlin.collections.List<LinkEntity>

)

