package de.fantjastisch.cards_backend.util.validation.errors;

public enum ErrorCode {
    CONSTRAINT_VIOLATION,
    NOT_NULL_VIOLATION,
    NOT_BLANK_VIOLATION,
    LABEL_TAKEN_VIOLATION,
    QUESTION_DUPLICATE_VIOLATION,
    SUBCATEGORY_DOESNT_EXIST_VIOLATION,
    CATEGORY_NOT_EMPTY_VIOLATION,
    CYCLIC_SUBCATEGORY_RELATION_VIOLATION,
    SUBCATEGORY_IS_NULL_VIOLATION,
}